name: "Checkout and Build"
description: ""
inputs:
  token:
    description: "Slack Token"
    required: false
    default: ''
  channel:
    description: "Channel ID to publish the message on"
    required: false
    default: ''
  ts:
    description: "Message ID to update"
    required: false
    default: ''
  force:
    description: "Force new message"
    required: false
    default: 'false'
  heading:
    description: "Heading"
    required: false
    default: ''
  action-url:
    description: "Action URL"
    required: false
    default: ''
  status:
    description: "Status"
    required: false
    default: ''
  final-status:
    description: "Final Status"
    required: false
    default: ''
  commit-message:
    description: "Commit message"
    required: false
    default: ''
  commit-branch:
    description: "Commit branch"
    required: false
    default: ''
  commit-repo:
    description: "Commit repo"
    required: false
    default: ''
  commit-author:
    description: "Commit author"
    required: false
    default: ''
  data-file:
    description: "the path to a file that will be posted on a thread"
    required: false
    default: ''
  data-blob:
    description: "A piece of data that will be posted as a file on a thread"
    required: false
    default: ''
    

runs:
  using: "composite"
  steps:
    - name: Setup token
      if: ${{ inputs.token != '' }}
      shell: bash
      run: echo -n "${{ inputs.token }}" > "$RUNNER_TEMP/slack.token"

    - name: Setup channel
      if: ${{ inputs.channel != '' }}
      shell: bash
      run: echo -n "${{ inputs.channel }}" > "$RUNNER_TEMP/slack.channel"

    - name: Setup TS
      if: ${{ inputs.ts != '' }}
      shell: bash
      run: echo -n "${{ inputs.ts }}" > "$RUNNER_TEMP/slack.ts"

    - name: Force new message
      if: ${{ inputs.force != 'false' }}
      shell: bash
      run: rm -rf "$RUNNER_TEMP/slack.ts"

    - name: Load token
      id: prepare
      shell: bash
      env:
        HEADING: ${{ inputs.heading }}
        ACTION_URL: ${{ inputs.action-url }}
        FINAL_STATUS: ${{ inputs.final-status }}
        STATUS: ${{ inputs.status }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        COMMIT_BRANCH: ${{ inputs.commit-branch }}
        COMMIT_REPO: ${{ inputs.commit-repo }}
        COMMIT_AUTHOR: ${{ inputs.commit-author }}
      run: "${{ github.action_path }}/prepare-message.sh"

    - name: Send Slack Message (Blocks)
      uses: archive/github-actions-slack@master
      if: ${{ steps.prepare.outputs.token != '' && steps.prepare.outputs.channel != '' && steps.prepare.outputs.function == 'send-message' }}
      id: send-message
      with:
        slack-function: "${{ steps.prepare.outputs.function }}"
        slack-bot-user-oauth-access-token: "${{ steps.prepare.outputs.token }}"
        slack-channel: "${{ steps.prepare.outputs.channel }}"
        slack-blocks: "${{ steps.prepare.outputs.blocks }}"

    - name: Setup TS
      if: ${{ steps.prepare.outputs.token != '' && steps.prepare.outputs.channel != '' && steps.prepare.outputs.function == 'send-message' }}
      shell: bash
      run: echo -n "${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}" > "$RUNNER_TEMP/slack.ts"

    - name: Update Slack Message (Blocks)
      uses: archive/github-actions-slack@master
      if: ${{ steps.prepare.outputs.token != '' && steps.prepare.outputs.channel != '' && steps.prepare.outputs.function == 'update-message' }}
      id: update-message
      with:
        slack-function: "${{ steps.prepare.outputs.function }}"
        slack-bot-user-oauth-access-token: "${{ steps.prepare.outputs.token }}"
        slack-channel: "${{ steps.prepare.outputs.channel }}"
        slack-update-message-blocks: "${{ steps.prepare.outputs.blocks }}"
        slack-update-message-ts: "${{ steps.prepare.outputs.ts }}"

    - name: Post a file to thread
      if: ${{ steps.prepare.outputs.token != '' && steps.prepare.outputs.channel != '' && inputs.data-file != '' }}
      shell: bash
      run: |
        if [ "${{ steps.prepare.outputs.ts }}" != "" ]; then
          SLACK_TS="${{ steps.prepare.outputs.ts }}"
        else
          SLACK_TS=$(<$RUNNER_TEMP/slack.ts)
        fi
        curl -F file=@${{ inputs.data-file }} -F "initial_comment=${{ inputs.commit-message }}" -F channels=${{ steps.prepare.outputs.channel }} -F thread_ts=$SLACK_TS -H "Authorization: Bearer ${{ steps.prepare.outputs.token }}" https://slack.com/api/files.upload


    - name: Post a data blob as a file to thread
      if: ${{ steps.prepare.outputs.token != '' && steps.prepare.outputs.channel != '' && inputs.data-blob != '' }}
      shell: bash
      run: |
        if [ "${{ steps.prepare.outputs.ts }}" != "" ]; then
          SLACK_TS="${{ steps.prepare.outputs.ts }}"
        else
          SLACK_TS=$(<$RUNNER_TEMP/slack.ts)
        fi
        echo -n "${{ inputs.data-blob }}" > "$RUNNER_TEMP/slack-data-blob"
        curl -F file=@$RUNNER_TEMP/slack-data-blob -F "initial_comment=${{ inputs.commit-message }}" -F channels=${{ steps.prepare.outputs.channel }} -F thread_ts=$SLACK_TS -H "Authorization: Bearer ${{ steps.prepare.outputs.token }}" https://slack.com/api/files.upload
